[type:feat] support e2e contain in k8s

diff --git a/shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-http/k8s/shenyu-deployment-mysql.yml b/shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-http/k8s/shenyu-deployment-mysql.yml
--- a/shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-http/k8s/shenyu-deployment-mysql.yml
+++ b/shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-http/k8s/shenyu-deployment-mysql.yml
@@ -31,20 +31,20 @@ spec:
         app: shenyu-admin-mysql
     spec:
       initContainers:
-        - name: download-mysql-jar
-          image: busybox:1.35.0
-          command: [ "sh","-c" ]
-          args: [ "wget https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.29/mysql-connector-java-8.0.29.jar;
-                  wget https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.29/mysql-connector-java-8.0.29.jar.md5;
-                  if [ $(md5sum mysql-connector-java-8.0.29.jar | cut -d ' ' -f1) = $(cat mysql-connector-java-8.0.29.jar.md5) ];
-                  then echo success;
-                  else echo failed;
-                  exit 1;
-                  fi;
-                  mv /mysql-connector-java-8.0.29.jar /opt/shenyu-admin/ext-lib/mysql-connector-java.jar" ]
-          volumeMounts:
-            - name: mysql-connector-volume
-              mountPath: /opt/shenyu-admin/ext-lib
+#        - name: download-mysql-jar
+#          image: busybox:1.35.0
+#          command: [ "sh","-c" ]
+#          args: [ "wget https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.29/mysql-connector-java-8.0.29.jar;
+#                  wget https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.29/mysql-connector-java-8.0.29.jar.md5;
+#                  if [ $(md5sum mysql-connector-java-8.0.29.jar | cut -d ' ' -f1) = $(cat mysql-connector-java-8.0.29.jar.md5) ];
+#                  then echo success;
+#                  else echo failed;
+#                  exit 1;
+#                  fi;
+#                  mv /mysql-connector-java-8.0.29.jar /opt/shenyu-admin/ext-lib/mysql-connector-java.jar" ]
+#          volumeMounts:
+#            - name: mysql-connector-volume
+#              mountPath: /opt/shenyu-admin/ext-lib
         - name: wait-mysql
           image: busybox:1.35.0
           command: [ "sh","-c" ]
@@ -88,15 +88,13 @@ spec:
           ports:
             - containerPort: 9096
           imagePullPolicy: IfNotPresent
-#          volumeMounts:
-#            - name: mysql-connector-volume
-#              mountPath: /opt/shenyu-admin/ext-lib
+          volumeMounts:
+            - name: mysql-connector-volume
+              mountPath: /opt/shenyu-admin/ext-lib
       volumes:
         - name: mysql-connector-volume
-          emptyDir: { }
-#        - name: mysql-connector-volume
-#          hostPath:
-#            path: /opt/shenyu-admin/ext-lib
+          hostPath:
+            path: /tmp/shenyu-e2e/driver/mysql
       restartPolicy: Always
 
 ---
